### ISSUE TITLE
twitter api must be authenticated

### ISSUE THREAD

**Issue by victoriagomezv** [tommeagher/heroku_ebooks#65] opened 2019-11-15 15:37 UTC
keep running into this issue when running heroku worker

![image](https://user-images.githubusercontent.com/57805291/68955207-80295200-0793-11ea-8adb-18f3421dfeee.png)

when i run "heroku config" my API keys show up fine

i did change the local settings file because a tutorial i followed prompted me to replace the Haroku variables with the keys themselves (Tom himself said not to do so) but still having the same issue

have a feeling it may have to do with this Twitter request, i don't see steps for filling it in any tutorial but it's requested of me when I create a new dev app. I had it previously filled with "http://127.0.0.1/twitter/callback" per a Google search but think that might be the culprit as it relates to oAuth

![image](https://user-images.githubusercontent.com/57805291/68955377-e1e9bc00-0793-11ea-8830-2c260830c73a.png)

**Comment by tommeagher** [comment] 2019-11-16 14:46
I’m not sure about that callback URL. We’re authenticating with the API so it shouldn’t be an issue and the instructions on that screenshot say to leave those blank. 

Would you mind sending me a screenshot of your heroku config output and your local_settings.py so I can troubleshoot locally on my end? Here’s [how to email me](http://www.tommeagher.com/about).

**Comment by samiaab1990** [comment] 2020-01-01 03:09
Hi there! I'm having the same exact issue. Here's what comes out of my command prompt on PC
<img width="547" alt="2019-12-31 22_04_33-Select Command Prompt" src="https://user-images.githubusercontent.com/39127633/71637759-22a17580-2c1a-11ea-9eff-d2e5e697a33e.png">

**Comment by samiaab1990** [comment] 2020-01-01 03:10
Hi there! I'm having the same exact issue. Here's what comes up on my command prompt:
<img width="547" alt="2019-12-31 22_04_33-Select Command Prompt" src="https://user-images.githubusercontent.com/39127633/71637768-5aa8b880-2c1a-11ea-8555-6aaaae7995c4.png">

**Comment by tommeagher** [comment] 2020-01-03 22:19
@samiaab1990, can you share your heroku config output and local_settings.py so I try it on my end? Here’s [how to email me](http://www.tommeagher.com/about).

**Comment by tommeagher** [comment] 2020-01-03 22:21
Also, this looks likely to be a duplicate of https://github.com/tommeagher/heroku_ebooks/issues/57 Can you read that thread to see if it helps solve this? @samiaab1990 @victoriagomezv

**Comment by samiaab1990** [comment] 2020-01-04 22:20
> Also, this looks likely to be a duplicate of #57 Can you read that thread to see if it helps solve this? @samiaab1990 @victoriagomezv

Hi, thanks for your response! The error message is the same but I didn't change my environ.get variables to the variables that were in the older version of local_settings. I will e-mail you my output.

**Comment by samiaab1990** [comment] 2020-01-04 23:58
> Also, this looks likely to be a duplicate of #57 Can you read that thread to see if it helps solve this? @samiaab1990 @victoriagomezv

Actually, this solved my issue! Thank you so much, I was in fact changing the insid

> Also, this looks likely to be a duplicate of #57 Can you read that thread to see if it helps solve this? @samiaab1990 @victoriagomezv

Actually, yes, this solved my issue! I was looking at an older tutorial where the local_settings.py contained the variables, so I was confused. Thank you so much.

I was additionally wondering if there is a way the bot can grab source tweets from private account, given that the private account is my main twitter account. I unlocked my account to test the bot but may want to put my account back on private in the future

**Comment by tommeagher** [comment] 2020-01-14 23:11
I haven’t looked at the API in quite a while, but I think if your bot follows your private account, this should work fine, @samiaab1990. 

@victoriagomezv  I’m going to close this issue as a duplicate but if that other solution doesn’t fix your issue, we can reopen this discussion.

**Closed by tommeagher** 2020-01-14 23:11 UTC
Labels: cant reproduce, duplicate
