### ISSUE TITLE
api authentification

### ISSUE THREAD

**Issue by techdecker** [tommeagher/heroku_ebooks#57] opened 2018-12-13 18:58 UTC
i'm running into this problem while doing "heroku run worker" in terminal I am not sure what to do about this.

<img width="714" alt="screen shot 2018-12-12 at 1 33 30 pm" src="https://user-images.githubusercontent.com/45857997/49960854-1e0b0180-fedf-11e8-839e-a451c476d448.png">

**Comment by tommeagher** [comment] 2018-12-23 13:34
Hey @techdecker, are you still getting this error? For some reason, Twitter isn't recognizing you as a user with the permissions to access to its API. Two culprits would be that you don't have the permissions yet or they aren't being read in from Heroku.

Did you add the POST permissions for your Twitter account at https://dev.twitter.com/apps ? 
Did you set your API keys as environment variables in Heroku, as in step 13 of [the README](https://github.com/tommeagher/heroku_ebooks/blob/master/README.md)?

**Comment by MRLmic** [comment] 2019-01-14 02:10
I'm having this issue too. @techdecker did this get resolved?

**Comment by tommeagher** [comment] 2019-01-15 02:34
Hi @MRLmic, no, @techdecker didn't reply. Did you add the permissions in Twitter and set your environment variables as in step 13?

**Comment by MRLmic** [comment] 2019-01-15 02:44
Hi @tommeagher I just did but my error message didn't change.

**Comment by KiNTan15** [comment] 2019-01-31 21:39
i get the same error
i add the permissions tokens and i have acces to twitter api

**Comment by KiNTan15** [comment] 2019-01-31 21:39
@tommeagher

**Comment by nozomiOwo** [comment] 2019-02-02 05:17
I've been having the same issues, I've done everything correctly, double check plenty of times and this error is still happening, my permissions are set to post, all my Access tokens and consumer API's are entered in both local_settings.py and through the command prompt commands, would love for this to work but this is the only problem I've been getting.
Any sort of fix would be appreciated.

**Comment by tommeagher** [comment] 2019-02-02 13:48
I have a pretty good hunch I know what the problem is. Think it has to do with the version of python-twitter in the requirements file. I’ll try to test a fix and cut a release in the next few days. 
Can one of you tell me what version of it is being installed when you push to Heroku?

**Comment by tommeagher** [comment] 2019-02-02 16:42
OK, so my hunch was wrong. In fact, I'm creating a fresh install of the app from Github and not able to replicate this problem. Which makes me think something in the README is unclear that's causing common confusion about the setup. It makes me think the API keys aren't making their way into Heroku correctly.

@nozomiOwo when you say "all my Access tokens and consumer API's are entered in both local_settings.py and through the command prompt commands", what did you change in local_settings.py?

**Comment by nozomiOwo** [comment] 2019-02-03 00:48
![notepad _ovyyx8vxm2](https://user-images.githubusercontent.com/47266201/52171031-2aa31d80-270a-11e9-9c30-f06ab100230b.png)
![image](https://user-images.githubusercontent.com/47266201/52171036-54f4db00-270a-11e9-8092-ed7e5a3e5c5c.png)
 
heres both the command prompt "heroku config" command and the locl_settings.py if you want an idea of what I mean

**Comment by tommeagher** [comment] 2019-02-03 14:11
Ahhh, @nozomiOwo, you shouldn’t change those fields in local_settings.py that you’ve blurred out. Those should remain the names of the Heroku config variables. Try changing those back and see if it works. I can update the docs to be more clear about that.

**Comment by MRLmic** [comment] 2019-03-10 00:21
Reverting my local_settings.py keys worked!

**Comment by tommeagher** [comment] 2019-03-10 16:04
@mrlmic, awesome. I’m glad to hear it. Do you think I can close this issue? Or do you have advice on how to improve the README or local_settings.py to make this easier?

**Comment by haleykim227** [comment] 2020-01-29 05:52
Could you please update the readme with this information? I was trying to resolve the problem for a couple hours until I found this thread. Thank you!

**Comment by tommeagher** [comment] 2020-01-30 12:09
hi @haleykim227. What part of the readme do you think we should update? I thought it was clear, but obviously it has been confusing for people and I'd like to make it easier. 

The README doesn't say anything about changing the twitter key values, does it? Do you have advice on what could make it easier? 

Also, did you come to this from a very old blog post? I know some people find that post which has old outdated instructions, and then comes here. I'm wondering if that's causing some of the confusion.

**Comment by MisterPoPcorn** [comment] 2020-07-21 19:18
I'm having this problem, and i can't find a solution. I was getting this problem, so after that i checked my heroku config, and no keys showed up, then i tried to add manually on the heroku website, again didn't work. In this print, on the highlighted part it was with the keys, but then i saw your comment saying you shouldn't mess it up, then i returned to the original text, but still doesn't work, also on twitter dev the permissions are right. Can you help me to see if i am missing something?  
![image](https://user-images.githubusercontent.com/34640347/88096352-e3625400-cb6c-11ea-8996-4aeb7d2a4d5a.png)

**Comment by tommeagher** [comment] 2020-07-26 17:34
@MisterPoPcorn, did you follow step 13 of the setup here? https://github.com/tommeagher/heroku_ebooks/#setup

**Comment by MisterPoPcorn** [comment] 2020-07-27 15:04
i missed the don't include quotes part, thank you very much

**Comment by tommeagher** [comment] 2020-07-27 15:23
@MisterPoPcorn did that fix it?

**Comment by desnadario** [comment] 2022-03-10 06:34
Ok, I'm having this issue as well, I triple-checked my auth keys, my apps permissions, and my global variables. I'm not sure what the issue is at this point after scouring the internet for hours

**Closed** 2022-03-14 15:48 UTC
Labels: Setup mistakes
