### ISSUE TITLE
Syntax Error "ebooks.py", line 69

### ISSUE THREAD

**Issue by Schwarzenegg** [tommeagher/heroku_ebooks#27] opened 2017-07-09 06:51 UTC
Hey there, I'm running into the issue below. I'm not familiar with the language so don't understand how to fix your syntax. Can you please advise? 

@tommeagher 

$ heroku run worker
Running worker on ⬢ guarded-brushlands-52122... up, run.7914 (Free)
  File "ebooks.py", line 69
    print ">>> Generating from {0}".format(file)
                                  ^
SyntaxError: invalid syntax
![screen shot 2017-07-09 at 4 49 50 pm](https://user-images.githubusercontent.com/8922765/27991826-c3ff4056-64c6-11e7-9767-962210d8428c.png)

**Comment by tommeagher** [comment] 2017-07-09 12:46
@Schwarzenegg, thanks for flagging this. I believe the problem is that Heroku now uses Python3 by default, but this library was written in Python 2.7. I just pushed a fix to the Github repo, if you want to use that, or simply add this [runtime.txt file](https://github.com/tommeagher/heroku_ebooks/blob/master/runtime.txt) to your project directory and push the change to Heroku. It should fix the issue. Let me know if it doesn't work.

**Closed by tommeagher** 2017-07-09 12:46 UTC
